added executor openapi spec
kubeshop/testkube-executor-template pull request #8
Opened 2021-09-13 10:41 UTC by exu

This PR...

## Changes

-

## Fixes

-

## Checklist

- [ ] tested locally
- [ ] added new dependencies
- [ ] updated the docs
- [ ] added a test

2021-09-13 10:42 UTC, exu commented
@olensmar it would be great to have somehow openapi spec generated for this one - but no website here any idea ? maybe some link in docs?

2021-09-15 06:04 UTC, olensmar commented on api/executor.yaml
> +        script-content:
let's do camelCase for properties

2021-09-15 06:05 UTC, olensmar commented on api/executor.yaml
> +      properties:
add required properties (goes for all objects)?

2021-09-15 06:05 UTC, olensmar commented on api/executor.yaml
> +  /executions/:
remove trailing slash

2021-09-15 06:08 UTC, olensmar commented on api/executor.yaml
> +          description: 'poblem with saving script details into queue'
poblem -> Problem

2021-09-15 06:08 UTC, olensmar commented on api/executor.yaml
> +      description: 'Gets execution with given ID, returns deailed information about test execution'
deailed -> detailed

2021-09-15 06:09 UTC, olensmar requested changes
see inline comments

2021-10-30 08:23 UTC, closed without merging